# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab6.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'lab6.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab6.proto\x12\x04lab6\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xc9\x01\n\x04Lab6\x12#\n\x03\x41\x64\x64\x12\x0c.lab6.addMsg\x1a\x0e.lab6.addReply\x12/\n\x08RawImage\x12\x11.lab6.rawImageMsg\x1a\x10.lab6.imageReply\x12\x38\n\nDotProduct\x12\x13.lab6.dotProductMsg\x1a\x15.lab6.dotProductReply\x12\x31\n\tJsonImage\x12\x12.lab6.jsonImageMsg\x1a\x10.lab6.imageReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab6_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMSG']._serialized_start=20
  _globals['_ADDMSG']._serialized_end=50
  _globals['_RAWIMAGEMSG']._serialized_start=52
  _globals['_RAWIMAGEMSG']._serialized_end=78
  _globals['_DOTPRODUCTMSG']._serialized_start=80
  _globals['_DOTPRODUCTMSG']._serialized_end=117
  _globals['_JSONIMAGEMSG']._serialized_start=119
  _globals['_JSONIMAGEMSG']._serialized_end=146
  _globals['_ADDREPLY']._serialized_start=148
  _globals['_ADDREPLY']._serialized_end=171
  _globals['_DOTPRODUCTREPLY']._serialized_start=173
  _globals['_DOTPRODUCTREPLY']._serialized_end=210
  _globals['_IMAGEREPLY']._serialized_start=212
  _globals['_IMAGEREPLY']._serialized_end=255
  _globals['_LAB6']._serialized_start=258
  _globals['_LAB6']._serialized_end=459
# @@protoc_insertion_point(module_scope)
